version: 0.2

env:
  parameter-store:
    S3Bucket: "/MyCICDPipeline/AppBucketName"

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm run build
      
  post_build:
    commands:
      - aws s3 sync build/ s3://$AppBucketName/ --delete
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths '/*'

artifacts:
  files:
    - '**/*'
  base-directory: build
