name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform CLI
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Step 3: Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Terraform Apply (Approve changes)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        
  build-and-test:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Clear npm cache
        run: |
          npm cache clean --force

      - name: defining working directory
        run: |
          mkdir -p ./naveen
          cd ./naveen

      - name: Install dependencies
        run: |
          npm install -g aws-cli
          npm install

      - name: check aws cli version
        run: aws --version

      - name: build project
        run: npm run build

      - name: remove node module
        run: rm -rf /home/runner/work/react-calculator/react-calculator/node_modules

      - name: List build folder contents
        run: |
          ls /home/runner/work/react-calculator/react-calculator
          ls -ltr build && pwd build  

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
        run: aws s3 cp ./build/ s3://react-calculator-build --recursive